services:
  user_generator:
    build:
      context: .
      dockerfile: UserGenerator/Dockerfile
    environment:
      GRPC_SERVER_HOST: "nginx"
      GRPC_SERVER_PORT: "50052"
    networks:
      - app-network
    ports:
      - "8082:8082"
    #deploy:
    #  replicas: 3
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  user_registrar:
    build:
      context: .
      dockerfile: UserRegistrar/Dockerfile
    depends_on:
      user_generator:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: nginx_load_balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    #depends_on:
    #  - user_generator
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge