server.port=8082
spring.application.name=user-generator
spring.config.import=grpc-config.yml

management.endpoint.shutdown.enabled=true
management.endpoints.web.exposure.include=health,info,shutdown
management.endpoint.health.show-details=always